blank_issues_enabled: false
contact_links:
  - name: Contacto directo (WhatsApp)
    url: https://wa.me/5493815658239
    about: Para consultas comerciales o de servicio técnico, contactanos directamente por WhatsApp.
